server:
  port: 8081
  ssl:
    enabled: true
    key-alias: scg
    key-store-password: scg1234
    key-store: classpath:scg-keystore.p12
    key-store-type: PKCS12
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
              - "http://34.66.179.100:3000"
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
            allowed-headers:
              - "*"
            allow-credentials: true
      routes:
        - id: auth-service
          uri: http://auth-service:8082/
          predicates:
          - Path=/api/authentication/**
          filters:
          - AuthenticationFilter

        - id: account-service
          uri: http://account-service:8083/
          predicates:
          - Path=/api/accounts/**
          filters:
            - AuthenticationFilter

        - id: reservation-service
          uri: http://reservation-service:8084/
          predicates:
            - Path=/api/reservation/**
          filters:
              - AuthenticationFilter

        - id: property-service
          uri: http://property-service:8085/
          predicates:
            - Path=/api/property/**
          filters:
            - AuthenticationFilter
            - AdminRouteFilter
