server:
  port: 8081
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8082/
          predicates:
          - Path=/authentication/**
          filters:
          - AuthenticationFilter


        - id: account-service
          uri: http://localhost:8083/
          predicates:
          - Path=/accounts/**
          filters:
            - AuthenticationFilter
            - AdminRouteFilter
