apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace:  external-services
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  # clusterIP: None
  type: NodePort
  selector:
    app: mongo