apiVersion: apps/v1
kind: Deployment
metadata:
  name: resevation-service
spec:
  selector:
    matchLabels:
      app: resevation-service
  replicas: 1
  template:
    metadata:
      labels:
        app: reservation-service
    spec:
      containers:
        - name: reservation-service
          image: nattystar/reservation:v1
          ports:
            - containerPort: 8083
          env:
            - name: DB_NAME 
              value: reservation
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: DB_USER_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: DB_PASSWORD
            - name: SIGN_KEY
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: SIGN_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: reservation-service
spec:
  ports:
    - protocol: "TCP"
      port: 8084
      targetPort: 8084
  selector:
    app: reservation-service
