apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: account-service-rule
spec:
  host: account-service
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 75
      http:
        http1MaxPendingRequests: 25
        maxRequestsPerConnection: 75
    outlierDetection:
      consecutive5xxErrors: 10
      interval: 1s
      baseEjectionTime: 2m
      maxEjectionPercent: 100

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: payment-service-rule
spec:
  host: payment-service
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 75
      http:
        http1MaxPendingRequests: 25
        maxRequestsPerConnection: 75
    outlierDetection:
      consecutive5xxErrors: 10
      interval: 1s
      baseEjectionTime: 2m
      maxEjectionPercent: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: property-service-rule
spec:
  host: property-service
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 75
      http:
        http1MaxPendingRequests: 25
        maxRequestsPerConnection: 75
    outlierDetection:
      consecutive5xxErrors: 10
      interval: 1s
      baseEjectionTime: 2m
      maxEjectionPercent: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reservation-service-rule
spec:
  host: reservation-service
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 75
      http:
        http1MaxPendingRequests: 25
        maxRequestsPerConnection: 75
    outlierDetection:
      consecutive5xxErrors: 10
      interval: 1s
      baseEjectionTime: 2m
      maxEjectionPercent: 100
