# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Project CICD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: docker.io
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Build and Push payment

    - name: push docker image
      run: mvn package dockerfile:push --file paypal/pom.xml
      env:
        MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push account

    - name: push docker image
      run: mvn package dockerfile:push --file account/pom.xml
      env:
        MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


#    - name: Build & push Docker image
#      uses: mr-smithers-excellent/docker-build-push@v5
#      with:
#        image: nattystar/paypal
#        tags: v1
#        registry: docker.io
#        dockerfile: paypal/Dockerfile
#        MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#        MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
